export { default as Home } from './Home'
export { default as Registration } from './Registration'
export { default as Login } from './Login'
export { default as NotFound } from './NotFound'
export { default as JobPage } from './JobPage'
export { default as UserProfile } from './UserProfile'
export { default as About } from './About'
export { default as Companies } from './Companies'
